// <auto-generated />
namespace Ecommerce_B2C_dotnet_FrontEnd.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class addRolesTable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addRolesTable));
        
        string IMigrationMetadata.Id
        {
            get { return "202109161242052_addRolesTable"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
